_MACOSX_DEPLOYMENT_TARGET_:
  - "10.15"
  - "11.1"

cross_target_platform:
  - osx-64
  - osx-arm64

OSX_SDK_DIR:
  - /opt
  - /Library/Developer/CommandLineTools/SDKs

zip_keys:
  - _MACOSX_DEPLOYMENT_TARGET_
  - cross_target_platform
  - OSX_SDK_DIR
