MACOSX_SDK_VERSION:
- '11.0'
_MACOSX_DEPLOYMENT_TARGET_:
- '15.1'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_target_platform:
- osx-64
docker_image:
- quay.io/condaforge/linux-anvil-x86_64:alma9
